framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=async'
            cache: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=cache'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'
            cron:
                dsn: 'cron://'
                retry_strategy:
                    max_retries: 0 # do not retry

        routing:
            # buy
            App\Bot\Application\Messenger\Job\PushOrdersToExchange\PushRelevantBuyOrders: async

            # from cron
            App\Bot\Application\Command\Exchange\TryReleaseActiveOrders: async
            App\Bot\Application\Command\Exchange\IncreaseHedgeSupportPositionByGetProfitFromMain: async

            # utils
            App\Bot\Application\Messenger\Job\Utils\FixupOrdersDoubling: async
            App\Bot\Application\Messenger\Job\Utils\MoveStopOrdersWhenPositionMoved: async

            # cache
            App\Bot\Application\Messenger\Job\Cache\UpdateTicker: cache

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
