monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - app_error
        - app_notification
        - connection_error
    handlers:
        app_errors:
            type: stream
            path: "%kernel.logs_dir%/app_errors.log"
            channels: [ app_error ]
        app_notifications:
            type: stream
            path: "%kernel.logs_dir%/app_notifications.log"
            channels: [ app_notification ]
        connection_errors:
            type: stream
            path: "%kernel.logs_dir%/connection_errors.log"
            channels: [ connection_error ]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: warning
                channels: ["!event", "!app_error", "!app_notification", "!connection_error"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!app_error",  "!app_notification", "!connection_error"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!app_error", "!app_notification", "!connection_error"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            app_errors:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%/app_errors.log"
                channels: [ app_error ]
            app_notifications:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%/app_notifications.log"
                channels: [ app_notification ]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
                channels: ["!event", "!app_error", "!app_notification", "!connection_error"]
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!app_error",  "!app_notification", "!connection_error"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
