framework:
    rate_limiter:
        ignore_buy_throttling:
            # use 'sliding_window' if you prefer that policy
            policy: 'fixed_window'
            limit: 1
            interval: '30 seconds'
        check_balance_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '1 minute'
        connection_errors_log_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '5 seconds'
        ticker_updated_log_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '10 seconds'
        btcusdt_ticker_updated_log_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '3 seconds'
        position_in_loss_alert_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '1 minute'
        position_in_profit_alert_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '30 seconds'
