version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - ./docker/etc/supervisor.d:/etc/supervisor.d
    command: ['/usr/bin/supervisord', '-c', '/etc/supervisord.conf', '-n']
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DATABASE}?serverVersion=${POSTGRES_VERSION:-15}
      MAKE_FROM_CONTAINER: "1"
#    networks:
#      - bot-network

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
#    networks:
#      - bot-network

volumes:
  php_socket:
#  caddy_data:
  db-data:
#  caddy_config:

#networks:
#  bot-network:
#    driver: "bridge"
