imports:
    - { resource: doctrine.yaml }

# @todo move to sandbox module
framework:
    rate_limiter:
        symbol_initialize_exception_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '5 minute'
        
        # can delete
        cannot_find_history_for_symbol_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '10 minutes'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Trading\:
        resource: '../../../'
        exclude: '../../../SDK'

    App\Trading\Application\Order\ContextShortcut\ContextShortcutRootProcessor:
        arguments:
            $processors: !tagged_iterator trading.order.contextShortcutProcessor

    App\Trading\Contract\ContractBalanceProviderInterface:
        class: App\Trading\Infrastructure\Cache\CachedContractBalanceProvider
        arguments:
            $innerProvider: '@App\Trading\Application\Provider\ContractBalanceProvider'

    periodicalOrder.cacheWrapper:
        class: App\Infrastructure\Cache\SymfonyCacheWrapper
        arguments:
            $cache: '@periodicalOrder.cache'

    App\Trading\Application\Job\PeriodicalOrder\PeriodicalOrderJobCache:
        arguments:
            $cache: '@periodicalOrder.cacheWrapper'

    App\Trading\Application\Parameters\TradingParametersProviderInterface:
        alias: App\Trading\Application\Parameters\TradingDynamicParameters
        public: true
