imports:
    - { resource: doctrine.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Trading\:
        resource: '../../../'
        exclude: '../../../SDK'

    App\Trading\Application\Order\ContextShortcut\ContextShortcutRootProcessor:
        arguments:
            $processors: !tagged_iterator trading.order.contextShortcutProcessor

# @todo move to sandbox module
framework:
    rate_limiter:
        unexpected_sandbox_exception_while_check_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '20 minutes'
        symbol_initialize_exception_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '5 minute'
        
        # can delete
        cannot_find_history_for_symbol_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '10 minutes'
