services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Trading\:
        resource: '../../../'
        exclude: '../../../SDK'

    # dynamic parameters evaluation
    App\Trading\Application\Parameters\TradingDynamicParameters:
        public: true
