imports:
    - { resource: doctrine.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Trading\:
        resource: '../../../'
        exclude: '../../../SDK'

    # dynamic parameters evaluation
    App\Trading\Application\Parameters\TradingDynamicParameters:
        public: true

    _instanceof:
        App\Trading\Application\Order\ContextShortcut\Processor\ShortcutContextProcessorInterface:
            tags: ['trading.order.contextShortcutProcessor']

    App\Trading\Application\Order\ContextShortcut\ContextShortcutRootProcessor:
        arguments:
            $processors: !tagged_iterator trading.order.contextShortcutProcessor

# @todo move to sandbox module
framework:
    rate_limiter:
        unexpected_sandbox_exception_while_check_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '20 minutes'
