### \App\Trading\Application\Settings\SafePriceDistanceSettings
safePriceDistance.baseMultiplier: 1    
safePriceDistance.applyStrategy: 'conservative'

# percent override
# safePriceDistance.percent[symbol=BTCUSDT]: 6              # example with symbol
# safePriceDistance.percent[symbol=BTCUSDT][side=sell]: 6   # example with symbol and side

### \App\Trading\Application\Settings\OpenPositionSettings
# 10% of whole risked balance will be opened with 4 delayed BuyOrders in -100%..100% range from position entry, ...
#openPosition.splitToBuyOrders.defaultGridsDefinition[symbol=AI16ZUSDT]: '-100%%..100%%|10%%|4|wOO;-200%%..200%%|30%%|10'
#openPosition.stops.defaultGridsDefinition[symbol=AI16ZUSDT]: '-100%%..-120%%|50%%|2;-200%%..-220%%|30%%|6'

### \App\Trading\Application\Settings\CoverLossSettings
trading.coverLoss.enabled: true
trading.coverLoss.bySpotBalance.enabled: false
trading.coverLoss.otherSymbols.additionalStop.distance: very-very-short






# for tests
trading.coverLoss.enabled[symbol=A8USDT][side=sell]: false
trading.coverLoss.enabled[symbol=A8USDT][side=buy]: true
trading.coverLoss.otherSymbols.additionalStop.distance[side=buy]: standard
