### \App\Liquidation\Application\Settings\LiquidationHandlerSettings
liquidationHandlerSettings.transferFromSpot.defaultAmount: 15
liquidationHandlerSettings.lastPriceCrossingThresholdDefaultCacheTtl: 150
liquidationHandlerSettings.CriticalPartOfLiquidationDistance: 20
liquidationHandlerSettings.percentOfLiquidationDistanceToAddStop: '50%'
liquidationHandlerSettings.acceptableStoppedPartFallback: 4
liquidationHandlerSettings.fixOpposite.if.oppositeBecameMain: true
liquidationHandlerSettings.fixOpposite.evenIf.oppositeIsSupport: false
liquidationHandlerSettings.afterStop.addOppositeBuyOrders: true

# @todo Must be based on current price? or volatility
liquidationHandlerSettings.actualStopsRangeFromAdditionalStop: 50
liquidationHandlerSettings.actualStopsRangeFromAdditionalStop[symbol=BTCUSDT]: 15
liquidationHandlerSettings.actualStopsRangeFromAdditionalStop[symbol=ETHUSDT]: 20
liquidationHandlerSettings.actualStopsRangeFromAdditionalStop[symbol=BNBUSDT]: 20

# @todo Must be (somehow) calculated automatically based on symbol volatility statistics (+ based on some `aggressive` / `conservative` [selected automatically in some situation and by config in common cases])
liquidationHandlerSettings.criticalDistancePnl: 200
liquidationHandlerSettings.criticalDistancePnl[symbol=BTCUSDT]: 50
liquidationHandlerSettings.criticalDistancePnl[symbol=ETHUSDT]: 80
