### \App\Trading\Application\Settings\SafePriceDistanceSettings
liquidationHandlerSettings.warningDistancePnl: 300
liquidationHandlerSettings.warningDistancePnl[symbol=BTCUSDT]: 70
liquidationHandlerSettings.warningDistancePnl[symbol=ETHUSDT]: 100

liquidationHandlerSettings.warningDistancePnlPercent.max: 1500
liquidationHandlerSettings.warningDistancePnlPercent.atr.period: 7
liquidationHandlerSettings.warningDistancePnlPercent.atr.multiplier: 0.5
