services:
    Symfony\Contracts\HttpClient\HttpClientInterface:
        class: App\Tests\Stub\SymfonyHttpClientStub

    App\Delivery\Application\Service\Geo\DistanceCalculatorInterface:
        public: true

    App\Delivery\Application\Service\Geo\GeoObjectProviderInterface:
        public: true
