# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $depotAddress: '%env(DEPOT_ADDRESS)%'
            $yandexApiKey: '%env(YANDEX_API_KEY)%'
            $slForcedTriggerDelta: '%env(float:SL_FORCED_TRIGGER_DELTA)%'
            $hedgeSupportPositionCreateOppositeStopAfter: '%env(HEDGE_SUPPORT_POSITION_CREATE_OPPOSITE_STOP_AFTER)%'
            $hedgeMainPositionCreateOppositeStopAfter: '%env(HEDGE_MAIN_POSITION_CREATE_OPPOSITE_STOP_AFTER)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/modules/'
            - '../src/Kernel.php'

    App\Delivery\:
        resource: '../src/modules/Delivery'

    App\Bot\:
        resource: '../src/modules/Bot'

    App\Controller\:
        resource: '../src/Controller'
        tags:
            - 'controller.service_arguments'

    App\Messenger\SchedulerTransport\TransportFactory:
        tags: [ 'messenger.transport_factory' ]

    App\Messenger\SchedulerTransport\Scheduler:
        factory: [ 'App\Messenger\SchedulerTransport\SchedulerFactory', 'createScheduler' ]

    App\Bot\Infrastructure\ByBit\PositionService:
        arguments:
            $apiKey: '%env(BYBIT_API_KEY)%'
            $apiSecret: '%env(BYBIT_API_SECRET)%'
            $cache: '@cache.filesystem_shared_pool'

    App\Bot\Infrastructure\ByBit\ExchangeService:
        arguments:
            $apiKey: '%env(BYBIT_API_KEY)%'
            $apiSecret: '%env(BYBIT_API_SECRET)%'
            $cache: '@cache.filesystem_shared_pool'

#    Symfony\Contracts\Cache\CacheInterface:
#        class: Symfony\Component\Cache\Adapter\ApcuAdapter

    app.cache_shared_filesystem_adapter:
        parent: 'cache.adapter.filesystem'
        tags:
            - { name: 'cache.pool', namespace: 'shared' }

    app.cache_shared_apcu_adapter:
        parent: 'cache.adapter.apcu'
        tags:
            - { name: 'cache.pool', namespace: 'shared' }

    App\Bot\Application\Events\LoggingListener:
        tags:
            - { name: 'kernel.event_subscriber', priority: -100}
