# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/modules/'
            - '../src/Kernel.php'

    App\Bot\:
        resource: '../src/modules/Bot'

### schedule
    App\Messenger\SchedulerTransport\TransportFactory:
        tags: [ 'messenger.transport_factory' ]

    App\Messenger\SchedulerTransport\Scheduler:
        factory: [ 'App\Messenger\SchedulerTransport\SchedulerFactory', 'createScheduler' ]

### exchange services
    App\Bot\Application\Service\Exchange\PositionServiceInterface:
        alias: App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearPositionCacheDecoratedService

    App\Bot\Application\Service\Exchange\ExchangeServiceInterface:
        alias: App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearExchangeCacheDecoratedService

    App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearExchangeCacheDecoratedService:
        class: App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearExchangeCacheDecoratedService
        arguments:
            $exchangeService: '@App\Infrastructure\ByBit\Service\ByBitLinearExchangeService'

    App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearPositionCacheDecoratedService:
        class: App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearPositionCacheDecoratedService
        arguments:
            $positionService: '@App\Infrastructure\ByBit\Service\ByBitLinearPositionService'

### cache
    App\Bot\Application\Service\Exchange\TickersCache:
        alias: App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearExchangeCacheDecoratedService

#    Symfony\Contracts\Cache\CacheInterface:
#        class: Symfony\Component\Cache\Adapter\ApcuAdapter

    app.cache_shared_filesystem_adapter:
        parent: 'cache.adapter.filesystem'
        tags:
            - { name: 'cache.pool', namespace: 'shared' }

    app.cache_shared_apcu_adapter:
        parent: 'cache.adapter.apcu'
        tags:
            - { name: 'cache.pool', namespace: 'shared' }

### events
    App\Bot\Application\Events\LoggingListener:
        tags:
            - { name: 'kernel.event_subscriber', priority: -100}

    App\Infrastructure\EventListener\DomainEvents\TriggerDomainEventsListener:
        tags:
            - { name: doctrine.event_listener, event: postFlush, method: postFlush }

    App\Infrastructure\ByBit\API\V5\ByBitV5ApiClient:
        class: App\Infrastructure\ByBit\API\V5\ByBitV5ApiClient
        arguments:
            $host: 'https://%env(BYBIT_API_HOST)%'
            $apiKey: '%env(BYBIT_API_KEY)%'
            $secretKey: '%env(BYBIT_API_SECRET)%'

    App\Application\Messenger\CheckPositionIsUnderLiquidationHandler:
        arguments:
            $positionService: '@App\Infrastructure\ByBit\Service\ByBitLinearPositionService' # without cache

### commands
    App\Command\Position\OpenCommand:
        class: App\Command\Position\OpenCommand
        arguments:
            $positionService: '@App\Infrastructure\ByBit\Service\ByBitLinearPositionService' # without cache
