services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symfony\Contracts\HttpClient\HttpClientInterface:
        class: App\Tests\Stub\Request\SymfonyHttpClientStub
        arguments:
            $baseUri: 'https://%env(BYBIT_API_HOST)%'

    App\Application\UniqueIdGeneratorInterface:
        class: App\Tests\Mock\UniqueIdGeneratorStub

    App\Application\Messenger\Position\CheckPositionIsUnderLiquidation\CheckPositionIsUnderLiquidationHandler:
        arguments:
            $exchangeService: '@App\Bot\Application\Service\Exchange\ExchangeServiceInterface'
            $positionService: '@App\Infrastructure\ByBit\Service\ByBitLinearPositionService' # without cache
            $exchangeAccountService: '@App\Bot\Application\Service\Exchange\Account\ExchangeAccountServiceInterface'
            $orderService: '@App\Bot\Application\Service\Exchange\Trade\OrderServiceInterface'
            $stopService: '@App\Bot\Application\Service\Orders\StopServiceInterface'
            $stopRepository: '@App\Bot\Domain\Repository\StopRepositoryInterface'

    App\Clock\ClockInterface:
        public: true
        class: App\Clock\Clock

    Psr\Log\LoggerInterface:
        public: true
        class: App\Tests\PHPUnit\TestLogger

    App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearExchangeCacheDecoratedService:
        class: App\Infrastructure\ByBit\Service\CacheDecorated\ByBitLinearExchangeCacheDecoratedService
        arguments:
            $exchangeService: '@App\Infrastructure\ByBit\Service\ByBitLinearExchangeService'
            $externalCache: null

    App\TechnicalAnalysis\Application\Contract\TechnicalAnalysisToolsFactoryInterface:
        public: true
