imports:
    - { resource: settings.yaml }
    - { resource: doctrine.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Settings\:
        resource: '../../../'

    App\Settings\Application\Service\AppSettingsService:
        arguments:
            $storedValuesProviders:
                - '@App\Settings\Infrastructure\Storage\SymfonyConfigStoredSettingsProvider'
                - '@App\Settings\Infrastructure\Storage\DoctrineSettingsStorage'

    App\Settings\Infrastructure\Storage\SymfonyConfigStoredSettingsProvider:
        arguments:
            $settingsBag: '@app.settings'
