services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Settings\:
        resource: '../../../'

    App\Settings\Application\Service\AppSettingsProvider:
        arguments:
            $settingsBag: '@app.settings'

    app.settings:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        arguments:
            $parameters:
                # connection
                connection.check.enabled: '%env(bool:CHECK_CONNECTION_ENABLED)%'

                # trading
                trading.marketBuy.safePriceDistance: 3000

                # @todo | MAIN_POSITION_..._OPPOSITE_PRICE_DISTANCE, SUPPORT_..._OPPOSITE_PRICE_DISTANCE ?
                trading.opposite.BuyOrder.priceDistance.forLongPosition: 400
                trading.opposite.BuyOrder.priceDistance.forShortPosition: 300
