imports:
    - { resource: settings.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Settings\:
        resource: '../../../'

    App\Settings\Application\Service\AppSettingsProvider:
        arguments:
            $settingsBag: '@app.settings'
