imports:
    - { resource: settings.yaml }
    - { resource: doctrine.yaml }

parameters:
    settings.dump.dir: '%kernel.project_dir%/data/dump/settings'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Settings\:
        resource: '../../../'

    App\Settings\Application\Service\AppSettingsService:
        public: true
        arguments:
            $storedValuesProviders:
                - '@App\Settings\Infrastructure\Storage\SymfonyConfigStoredSettingsProvider'
                - '@App\Settings\Infrastructure\Storage\DoctrineSettingsStorage'

    App\Settings\Infrastructure\Storage\SymfonyConfigStoredSettingsProvider:
        arguments:
            $settingsBag: '@app.settings'

    App\Settings\Application\Parameters\AppParametersLocator:
        arguments:
            - '@service_container'

    App\Settings\Application\DynamicParameters\Evaluation\AppDynamicParameterEvaluator:
        arguments:
            - '@service_container'

    # dynamic parameters evaluation
    _instanceof:
        App\Settings\Application\DynamicParameters\DefaultValues\ParameterDefaultValueProviderInterface:
            public: true

    settings.cacheWrapper:
        class: App\Infrastructure\Cache\SymfonyCacheWrapper
        arguments:
            $cache: '@settings.cache'

    App\Settings\Application\Service\SettingsCache:
        arguments:
            $cache: '@settings.cacheWrapper'

    App\Settings\UI\Symfony\Command\Settings\Dump\SettingsDumpRestoreCommand:
        arguments:
            $defaultSettingsPath: '%settings.dump.dir%'
