services:
    app.settings:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        arguments:
            $parameters:
                # connection
                connection.check.enabled: '%env(bool:CHECK_CONNECTION_ENABLED)%'

                # trading
                trading.marketBuy.safePriceDistance: 5000

                # @todo | MAIN_POSITION_..._OPPOSITE_PRICE_DISTANCE, SUPPORT_..._OPPOSITE_PRICE_DISTANCE ?
                trading.opposite.BuyOrder.pnlDistance.forLongPosition: '50%'
                trading.opposite.BuyOrder.pnlDistance.forShortPosition: '50%'

                trading.opposite.BuyOrder.altCoin.pnlDistance.forLongPosition: '200%'
                trading.opposite.BuyOrder.altCoin.pnlDistance.forShortPosition: '200%'

                # push Stop
                push.stop.cover_loss_after_close_by_market.enabled: true
                push.stop.mainPositionSafeLiqDistance.afterPushSupportPositionStops: 5000

                # push BuyOrder
                push.BuyOrder.checks.isLastPriceOverIndexPrice.enabled: false
                push.BuyOrder.checks.ignoreBuyBasedOnTotalPositionLeverage.enabled: false

                # other
                trading.takeProfitWhenBalanceIsInsufficient.enabled: false
                trading.takeProfitWhenBalanceIsInsufficient.afterProfitPercent: 170

                # by symbol-side
                # safePriceDistance.percent[symbol=ARCUSDT][side=sell]: 100
