services:
    # !!! @see SettingsDefaultValuesCompilerPass !!!
    app.settings:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        arguments:
            $parameters:
                alarm.priceAlarm.soundsCount: 6

                # profit / loss
                alarm.loss.enabled: false
                alarm.profit.enabled: false
                alarm.balance.greater: 'false'
                alarm.balance.less: 'false'
                alarm.liquidationDistance.passedPart.allowed: 50

                # connection
                connection.check.enabled: '%env(bool:CHECK_CONNECTION_ENABLED)%'
