services:
    # !!! @see SettingsDefaultValuesCompilerPass !!!
    app.settings:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        arguments:
            $parameters:
                # profit / loss
                alarm.loss.enabled: false
                alarm.profit.enabled: false

                # connection
                connection.check.enabled: '%env(bool:CHECK_CONNECTION_ENABLED)%'

                # @todo | MAIN_POSITION_..._OPPOSITE_PRICE_DISTANCE, SUPPORT_..._OPPOSITE_PRICE_DISTANCE ?
                trading.opposite.BuyOrder.pnlDistance.forLongPosition: '50%'
                trading.opposite.BuyOrder.pnlDistance.forShortPosition: '50%'

                trading.opposite.BuyOrder.altCoin.pnlDistance.forLongPosition: '200%'
                trading.opposite.BuyOrder.altCoin.pnlDistance.forShortPosition: '200%'

                # push Stop
                push.stop.cover_loss_after_close_by_market.enabled: true

                # push BuyOrder
                push.BuyOrder.checks.isLastPriceOverIndexPrice.enabled: false
                push.BuyOrder.checks.ignoreBuyBasedOnTotalPositionLeverage.enabled: false

# other
                trading.takeProfitWhenBalanceIsInsufficient.enabled: false
                trading.takeProfitWhenBalanceIsInsufficient.afterProfitPercent: 170

# Trading\Application\Settings\SafePriceDistanceSettings
                safePriceDistance.applyStrategy: 'conservative'
                # safePriceDistance.percent[symbol=BTCUSDT]: 6              # example with symbol
                # safePriceDistance.percent[symbol=BTCUSDT][side=sell]: 6   # example with symbol and side

# Liquidation\Application\Settings\LiquidationHandlerSettings
                liquidationHandlerSettings.CriticalPartOfLiquidationDistance: 20
                liquidationHandlerSettings.percentOfLiquidationDistanceToAddStop: '30%'
                liquidationHandlerSettings.acceptableStoppedPartFallback: 4
                liquidationHandlerSettings.fixOpposite.if.oppositeBecameMain: true
                liquidationHandlerSettings.fixOpposite.evenIf.oppositeIsSupport: false
                liquidationHandlerSettings.afterStop.addOppositeBuyOrders: true

                # @todo Must be based on current price? or volatility
                liquidationHandlerSettings.actualStopsRangeFromAdditionalStop: 50
                liquidationHandlerSettings.actualStopsRangeFromAdditionalStop[symbol=BTCUSDT]: 8
                liquidationHandlerSettings.actualStopsRangeFromAdditionalStop[symbol=ETHUSDT]: 20
                liquidationHandlerSettings.actualStopsRangeFromAdditionalStop[symbol=BNBUSDT]: 20

                # @todo Must be (somehow) calculated automatically based on symbol volatility statistics
                liquidationHandlerSettings.warningDistancePnl: 400
                liquidationHandlerSettings.warningDistancePnl[symbol=BTCUSDT]: 120
                liquidationHandlerSettings.warningDistancePnl[symbol=ETHUSDT]: 200
                liquidationHandlerSettings.warningDistancePnl[symbol=ARCUSDT]: 500
                liquidationHandlerSettings.warningDistancePnl[symbol=FARTCOINUSDT]: 500

                # @todo Must be (somehow) calculated automatically based on symbol volatility statistics
                liquidationHandlerSettings.criticalDistancePnl: 200
                liquidationHandlerSettings.criticalDistancePnl[symbol=BTCUSDT]: 60
                liquidationHandlerSettings.criticalDistancePnl[symbol=BTCUSDT][side=sell]: 60 # as example of default for symbol and side
                liquidationHandlerSettings.criticalDistancePnl[symbol=ETHUSDT]: 80
                liquidationHandlerSettings.criticalDistancePnl[symbol=ARCUSDT]: 200
                liquidationHandlerSettings.criticalDistancePnl[symbol=FARTCOINUSDT]: 200
