services:
    app.settings:
        class: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag
        arguments:
            $parameters:
                # connection
                connection.check.enabled: '%env(bool:CHECK_CONNECTION_ENABLED)%'

                # @todo | MAIN_POSITION_..._OPPOSITE_PRICE_DISTANCE, SUPPORT_..._OPPOSITE_PRICE_DISTANCE ?
                trading.opposite.BuyOrder.pnlDistance.forLongPosition: '50%'
                trading.opposite.BuyOrder.pnlDistance.forShortPosition: '50%'

                trading.opposite.BuyOrder.altCoin.pnlDistance.forLongPosition: '200%'
                trading.opposite.BuyOrder.altCoin.pnlDistance.forShortPosition: '200%'

                # push Stop
                push.stop.cover_loss_after_close_by_market.enabled: true

                # push BuyOrder
                push.BuyOrder.checks.isLastPriceOverIndexPrice.enabled: false
                push.BuyOrder.checks.ignoreBuyBasedOnTotalPositionLeverage.enabled: false

                # other
                trading.takeProfitWhenBalanceIsInsufficient.enabled: false
                trading.takeProfitWhenBalanceIsInsufficient.afterProfitPercent: 170

                # trading
                # safePriceDistance.percent[symbol=BTCUSDT]: 6              # example with symbol
                # safePriceDistance.percent[symbol=BTCUSDT][side=sell]: 6   # example with symbol and side

                # liquidationHandler
                liquidationHandlerSettings.CriticalPartOfLiquidationDistance: 20
