framework:
    rate_limiter:
        check_can_execute_support_stop_throttling:
            policy: 'fixed_window'
            limit: 1
            interval: '45 seconds'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Stop\:
        resource: '../../../'

    App\Stop\Application\UseCase\CheckStopCanBeExecuted\StopChecksChain:
        factory: [ '@App\Stop\Application\UseCase\CheckStopCanBeExecuted\StopChecksChainFactory', 'full' ]
