### \App\Bot\Application\Settings\PushStopSettings
push.stop.mainPositions.initialFilterPosition.ifStopsNotFound: true
push.stop.whichRangeToUse.while.chooseMarkPrice.asTriggerPrice: 'warning'

### Stop\Application\Settings\FixOppositePositionSettings
stop.afterStop.fixOppositePosition.enabled: true

stop.afterStop.fixOppositePosition.applyOnlyIf.oppositePositionPnl.greaterThan: '1000%' # @todo MB change some (all symbols)
stop.afterStop.fixOppositePosition.supplyStopPnlDistance: '300%'

stop.afterStop.fixOppositePosition.applyOnlyIf.oppositePositionPnl.greaterThan[symbol=FARTCOINUSDT]: '600%'
stop.afterStop.fixOppositePosition.supplyStopPnlDistance[symbol=FARTCOINUSDT]: '400%'

stop.afterStop.fixOppositePosition.applyOnlyIf.oppositePositionPnl.greaterThan[symbol=ETHUSDT]: '500%'
stop.afterStop.fixOppositePosition.supplyStopPnlDistance[symbol=ETHUSDT]: '200%'

stop.afterStop.fixOppositePosition.applyOnlyIf.oppositePositionPnl.greaterThan[symbol=BTCUSDT]: '300%'
stop.afterStop.fixOppositePosition.supplyStopPnlDistance[symbol=BTCUSDT]: '120%'

stop.movePositionStops.moveToBreakeven.after.positionPnlPercent: 900

### \App\Stop\Application\Settings\CreateOppositeBuySettings
stop.createOpposite.martingale.enabled: true
stop.createOpposite.martingale.enabled[side=sell]: true
stop.createOpposite.addForceFlag.enabled: true
